# Copyright (c) 2024, Hershel Theodore Layton
# Copies of this file can be made, with or without changes,
# under the terms of the MIT-0 license.

name: Continuous Integration
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "24 18 * * FRI"
jobs:
  build:
    name: HHVM ${{matrix.hhvm}}
    strategy:
      fail-fast: false
      matrix:
        hhvm:
          - "4.153"
          - "4.168"
          - "25.6.0"
          - "25.7.0"
    runs-on: ubuntu-24.04
    container:
      image: ${{ startsWith(matrix.hhvm, '4') && format('hhvm/hhvm:{0}-latest', matrix.hhvm) || format('hersheltheodorelayton/hhvm-full:{0}', matrix.hhvm) }}
    steps:
      - uses: actions/checkout@v2
      - name: Create branch for version alias
        run: |
          git config --global --add safe.directory $(pwd)
          git checkout -b CI_current_pull_request
      - uses: hershel-theodore-layton/actions/hack-lint-test@master
        with:
          hhvm: ${{matrix.hhvm}}
          hhvm_flags: ${{ startsWith(matrix.hhvm, '4') && '-dhhvm.autoload.enabled=true -dhhvm.autoload.db.path=.var/facts.db' || '' }}
          lint_engine: pha
          test_engine: test-chain
